name: "Version Updater"
author: "Paulo Sánchez"
description: "Updates the metadata file version for a package."
inputs:
  git-email:
    description: "Email used for the commit used to update the version."
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  git-name:
    description: "Name used for the commit used to update the version."
    required: false
    default: "GitHub Actions"
  target-file:
    description: "The file that contains package metadata."
    required: true
  commit-title:
    description: "The title of the commit used to update the version."
    required: false
    default: "Update version to {version}"
  commit-description:
    description: "The description of the commit used to update the version."
    required: false
    default: "The version of the package was updated to {version} based on the release triggered by @{author} in the {branch} branch."
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "chevrons-up"
  color: "gray-dark"
