name: "Version Updater"
author: "Paulo Sánchez"
description: "Updates the version of a package metadata file"
inputs:
  git-email:
    description: "Email used for git commits."
    required: false
    default: "action@github.com"
  git-name:
    description: "Name used for git commits."
    required: false
    default: "GitHub Action"
  target-file:
    description: "The file that contains package metadata."
    required: true
  commit-title:
    description: "The title of the commit used to update the version."
    required: false
    default: "Update version to {version}"
  commit-description:
    description: "The description of the commit used to update the version."
    required: false
    default: "The version of the package was updated to `{version}` based on the release triggered by @{author} in the `{branch}` branch."
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "chevrons-up"
  color: "gray-dark"
