name: Update README

on:
  release:
    types:
      - published
    branches:
      - stable

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run updater
        run: python3 .github/scripts/readme-updater.py ${{github.ref_name}}

      - name: Configure git
        run: |
          git config --global user.name "Paulo Sánchez"
          git config --global user.email "dev.szblzpaulo@gmail.com"

      - name: Commit and push README modifications
        run: |
          git commit README.md -m "Update version to ${{github.ref_name}}"
          git push origin HEAD:stable --force
