name: Update package version

on:
  release:
    types:
      - published
    branches:
      - stable

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          target-file: "package.json"
